[project]
name = "integrated-validation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.2",
    "psutil>=7.0.0",
    "pytest>=8.4.1",
    "pyyaml>=6.0.2",
]
